version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end
      - front-end

  back-end:
    build:
      context: ./server
    command: npm run dev
    networks:
      - node-network
    depends_on:
       - db

  front-end:
    build:
      context: ./client
    networks:
      - node-network

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    ports: 
      - "5432:5432"
    networks: 
      - node-network
  
networks: 
  node-network:
    driver: bridge