version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ed-dep-nginx
    restart: always
    ports:
      - "4005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
    depends_on:
      - back-end
      - front-end

  back-end:
    build:
      context: ./server
    container_name: back-end
    restart: always
    networks:
      - node-network
    depends_on:
       - db

  front-end:
    build:
      context: ./client
    container_name: front-end
    restart: always
    networks:
      - node-network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    networks: 
      - node-network
  
networks: 
  node-network:
    driver: bridge